version: '3.3'
services:
  db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: 'db'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password_db'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password_db'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3360:3306'
      # Where our data will be persisted
    volumes:
      - db:/var/lib/mysql
# Names our volume
volumes:
  db:
